const FaqList = [
    {
        id:1,
        question:"How often will my waste be evacuated?",
        answer:"2 times weekly."
    },
    {
        id:2,
        question:"What if I am not around, will my waste be evacuated?",
        answer:"Yes, your waste will be evacuated if it is well bagged and placed in an accessible place."
    },
    {
        id:3,
        question:"Can I still contact you if I need  an emergency evacuation to be  done outside the normal schedule?",
        answer:"Sure, you can call on us anytime but  an extra charge may be applicable."
    },
    {
        id:4,
        question:"What are the cost  and billing options for your service?",
        answer:"Our services are affordable, it depends on the size of the waste that has been generated by you and our payments are done by transfer to our company's account making it easy for  our customers to pay up their bills."
    },
    {
        id:5,
        question:"What should I do if I have questions and concerns about your services?",
        answer:"You can call or send text messages to our customer service lines, we will get back to you and address your concerns"
    }
    
    
]
export default FaqList